#!/usr/bin/python

"""
Train a 2 stage random forest classifier with a list of samples and segmentations.

Usage:
  train_from_multiple [-t=RT1TIV] TRAIN_LIST CLASSIFIER FVECS [MAXPERCLASS]
  train_from_multiple (-h|--help |--version)

Arguments:
  TRAIN_LIST:      A file listing directories, one per line, with both
                   feature vector and segmented .niis.
  CLASSIFIER:      The classifier parameters will be written as a modified
                   pickle to RFC_<CLASSIFIER>.joblib_dump.
  FVECS:           Get the feature vectors from dir/<FVECS> for each dir
                   in TRAIN_LIST.
  MAXPERCLASS:     Get up to this many samples of each class.
                   [default: 100000]

Options:
  -t RT1TIV --t1=RT1TIV     A T1-based TIV, already registered to diffusion
                            space.  If provided, a blurred copy of it will
                            be used as a prior.
  -h --help                 Show this message and exit.
  --version                 Show the version and exit.
"""
from docopt import docopt

import .train

# Please use semantic versioning (API.feature.bugfix), http://semver.org/
args = docopt(__doc__, version='0.9.0')

res, pfn, logfn = train.train_both_stages_from_multiple(args['TRAIN_LIST'],
                                                        args['CLASSIFIER'],
                                                        srclist_is_srcdirs=True,
                                                        fvfn=args['FVECS'],
                                                        maxperclass=args['MAXPERCLASS'],
                                                        rT1TIVfn=args.get('--t1'))
print "result:", res
print "classifier:", pfn
print "log file:", logfn


